(()=>{'use strict';
const main=document.getElementById('main'),sheet=document.getElementById('sheet'),card=document.getElementById('sheet-card');
const HOW={
'March in place':['Stand tall with feet hip-width apart.','Lift one knee at a time to a comfortable height.','Let the opposite arm swing naturally.','Keep your ribs stacked, breathe steadily and build rhythm gradually.'],
'Squat':['Stand with feet about shoulder-width apart.','Brace gently and send your hips back as you bend the knees.','Lower only as far as you can while keeping your whole foot grounded.','Drive through the floor to stand tall and squeeze the glutes.'],
'Incline push-up':['Place hands on a stable surface slightly wider than your shoulders.','Walk your feet back and make one straight line from head to heels.','Bend your elbows and lower your chest toward the surface.','Press the surface away and return without letting your hips sag.'],
'Dead bug':['Lie on your back with knees and hips bent to about 90 degrees.','Brace gently and keep your lower back comfortably supported.','Slowly extend the opposite arm and leg.','Return to the start and alternate sides without losing trunk control.'],
'Glute bridge':['Lie on your back with knees bent and feet flat.','Brace gently and keep your ribs relaxed.','Push through your heels and lift your hips.','Pause with the glutes squeezed, then lower slowly.'],
'Bird dog':['Start on hands and knees with a neutral spine.','Brace your trunk and reach one arm forward.','Extend the opposite leg back without rotating your hips.','Return slowly and switch sides.'],
'Push-up':['Start in a strong plank with hands just outside shoulder width.','Brace your trunk and keep your body in one line.','Lower your chest by bending the elbows under control.','Press the floor away to return to the top.'],
'Reverse lunge':['Stand tall with feet hip-width apart.','Step one foot back and lower both knees under control.','Keep the front foot planted and torso steady.','Push through the front foot to return and alternate.'],
'Hip hinge':['Stand tall with a soft bend in the knees.','Push your hips backward while keeping your spine long.','Move until you feel tension through the hamstrings.','Drive the hips forward to stand tall without over-arching.'],
'Plank':['Set your forearms or hands under your shoulders.','Extend the legs and create one line from head to heels.','Brace gently and squeeze the glutes.','Breathe normally while holding the position.'],
'Side plank':['Stack your elbow under your shoulder and extend your legs.','Brace your trunk and lift your hips.','Keep shoulders, hips and ankles aligned.','Breathe steadily, then lower with control and switch sides.'],
'Calf raise':['Stand tall with feet hip-width apart and use support if needed.','Rise smoothly onto the balls of your feet.','Pause briefly at the top.','Lower slowly until your heels are grounded.'],
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]) )}
function openCoach(name,detail){const steps=HOW[name]||['Set up in a stable position and choose a comfortable range of motion.','Move slowly through the full controlled range.','Keep your trunk stable and breathe normally.','Stop if you feel sharp pain, dizziness or unusual symptoms.'];card.innerHTML=`<div class="coach-sheet"><div class="sheet-handle"></div><div class="coach-visual"><div class="coach-pulse"></div><span>HOW TO</span></div><div class="eyebrow">${esc(detail||'EXERCISE')}</div><h2>${esc(name)}</h2><p class="sub">Follow the four cues below. Quality first, then reps.</p><div class="how-list">${steps.map((x,i)=>`<div class="how-step"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div><div class="coach-note"><strong>Form check</strong><span>Move under control. Keep breathing. Use a stable setup.</span></div><button class="primary coach-done" data-action="coach-close">Got it <span>✓</span></button></div>`;sheet.classList.add('open');sheet.setAttribute('aria-hidden','false')}
document.addEventListener('click',e=>{const x=e.target.closest('[data-action="exercise"]');if(x){e.preventDefault();e.stopImmediatePropagation();openCoach(x.dataset.name,x.dataset.detail)}},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-action="coach-close"]')){sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true')}},true);
})();