(()=>{'use strict';
const app=document.querySelector('#module-02');
const KEY='fitguide-foundation-v1',HKEY='fitguide-history-v4';
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v==null?f:v}catch{return f}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d=read(KEY,null);
if(!d||!d.goal||!d.experience||!d.days||!d.minutes||!d.environment){app.innerHTML='<section class="fallback"><div class="fallback-card"><div class="eyebrow">FITNESS GUIDE · MODULE 02</div><h1>Complete your foundation first.</h1><p>Today uses the profile created in Module 01.</p><button class="link" id="return">Return to foundation</button></div></section>';const b=document.querySelector('#return');if(b)b.onclick=()=>location.href='index.html';return;}
const goals={fat:'Lose body fat',muscle:'Build muscle',strength:'Build strength',fitness:'Improve fitness',habit:'Build consistency'};
const structures={fat:'Strength + conditioning',muscle:'Strength + hypertrophy',strength:'Strength + technique',fitness:'Strength + conditioning + mobility',habit:'Simple full-body consistency'};
const rawHistory=read(HKEY,[]),history=Array.isArray(rawHistory)?rawHistory:[],now=new Date(),dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const planned=Math.max(2,Math.min(7,Number(d.days)||3)),mins=Math.max(20,Math.min(120,Number(d.minutes)||30));
const start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-start.getDay());
const key=x=>`${x.getFullYear()}-${x.getMonth()}-${x.getDate()}`;
const validHistory=history.filter(x=>x&&x.date&&!Number.isNaN(new Date(x.date).getTime()));
const done=new Set(validHistory.map(x=>key(new Date(x.date))));
const sessions=validHistory.filter(x=>(now-new Date(x.date))>=0&&(now-new Date(x.date))<7*86400000).length;
function render(){const h=now.getHours(),g=h<12?'Good morning':h<18?'Good afternoon':'Good evening';const name=d.name||'there';const equipment=Array.isArray(d.equipment)&&d.equipment.length?d.equipment.join(' · '):'No equipment selected';app.innerHTML=`<div class="m02"><header class="topbar"><div class="logo"><i></i>Fitness Guide</div><div class="topmeta">TODAY</div></header><main class="home"><section class="hero"><div class="intro"><div class="eyebrow">FOR YOU · TODAY</div><h1>${esc(g)},<br>${esc(name)}.</h1><p class="lead">One clear starting point for today, built from the foundation you created.</p></div><article class="hero-card"><div><small>TODAY'S DIRECTION</small><strong>${esc(structures[d.goal]||'Balanced training')}</strong><span>${planned} days / week · ${mins} min · ${esc(d.environment)}</span></div><button class="primary" id="start">Start today's session <b>↗</b></button></article></section><section class="section"><div class="section-head"><div><div class="eyebrow">YOUR FOUNDATION</div><h2>Built around you.</h2></div></div><div class="cards"><article class="card"><small>PRIMARY GOAL</small><strong>${esc(goals[d.goal]||'Fitness')}</strong><span>Sets the direction for your training.</span></article><article class="card"><small>TRAINING WINDOW</small><strong>${mins} min</strong><span>Fits the session time you selected.</span></article><article class="card"><small>TRAINING SETUP</small><strong>${esc(d.environment)}</strong><span>${esc(equipment)}</span></article></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">THIS WEEK</div><h2>Your rhythm.</h2></div><span>${sessions} / ${planned} sessions logged</span></div><article class="rhythm"><div class="days">${[0,1,2,3,4,5,6].map(i=>{const x=new Date(start);x.setDate(start.getDate()+i);return `<div class="day ${key(x)===key(now)?'today':''} ${done.has(key(x))?'done':''}"><b>${dayNames[x.getDay()]}</b><i></i></div>`}).join('')}</div></article></section><section class="section"><div class="section-head"><div><div class="eyebrow">COACHING</div><h2>Keep the next choice simple.</h2></div></div><div class="insight"><article><strong>${sessions?'Momentum is already building.':'Your first session is the priority.'}</strong><p>${sessions?'Stay close to the schedule you chose and let consistency accumulate.':'You do not need to do everything today. Start with the session designed for your available time.'}</p></article><article><strong>${d.experience==='beginner'?'Build confidence before complexity.':d.experience==='advanced'?'Progress deliberately and protect movement quality.':'Keep technique consistent as the challenge increases.'}</strong><p>This principle will become an actionable training experience in Module 03.</p></article></div></section></main><footer class="bottom"><span>Module 02 · Today</span></footer></div>`;const b=document.querySelector('#start');if(b)b.onclick=()=>alert("Today's guided workout will be connected in Module 03: Train.");}
render();
})();