(()=>{'use strict';
const KEY='fitguide-foundation-v1';
const app=document.querySelector('#module-01');
const defaults={name:'',goal:'',age:'',sex:'',height:'',weight:'',experience:'',days:'',minutes:'',environment:'',equipment:[],diet:'',restrictions:'',trainingDays:[]};
let data={...defaults,...read()};let step=0;
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{}}catch{return {}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const goals=[['fat','Lose body fat','Reduce body fat while building sustainable habits.'],['muscle','Build muscle','Develop strength and muscle with progressive training.'],['strength','Build strength','Improve strength, technique and performance.'],['fitness','Improve fitness','Build a balanced base of strength, conditioning and mobility.'],['habit','Build consistency','Create a training routine you can realistically maintain.']];
const experiences=[['beginner','New to training','Little or no structured training experience.'],['intermediate','Some experience','You have trained before and know the basics.'],['advanced','Experienced','You train consistently and understand core movements.']];
const environments=[['gym','Full gym','Machines, cables, free weights and cardio.'],['home','Home','Train with what you have at home.'],['minimal','Minimal equipment','A small selection of weights or bands.'],['bodyweight','Bodyweight','No equipment required.']];
const diets=['Flexible / no specific preference','Vegetarian','Vegan','Non-vegetarian','High-protein preference'];
const equipment=['Dumbbells','Barbell + plates','Resistance bands','Bench','Pull-up bar','Kettlebell','Machines','Cardio equipment'];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(){return Math.round((step/7)*100)}
function selected(a,v){return a===v?'on':''}
function optionList(list,key){return `<div class="choices">${list.map(x=>`<button class="choice ${selected(data[key],x[0])}" data-choice="${key}" data-value="${x[0]}"><strong>${esc(x[1])}</strong><span>${esc(x[2])}</span></button>`).join('')}</div>`}
function stepView(){
if(step===0)return `<div class="step"><div class="eyebrow">FITNESS GUIDE · FOUNDATION</div><h1>Let’s build a plan that fits your life.</h1><p class="lead">Before we recommend training, we learn what you want, where you are starting, how much time you have and what you can realistically do.</p><button class="next" data-next="1">Get started ↗</button><p class="note">Your foundation is stored locally on this device. You can edit it later.</p></div>`;
if(step===1)return `<div class="step"><div class="eyebrow">01 · YOUR GOAL</div><h1>What do you want to change?</h1><p class="lead">Choose the outcome that matters most right now. Your primary goal shapes the starting direction.</p>${optionList(goals,'goal')}</div>`;
if(step===2)return `<div class="step"><div class="eyebrow">02 · YOUR BASELINE</div><h1>Give us the basics.</h1><p class="lead">These values help us understand your starting point. They are not a medical assessment.</p><div class="fields"><div class="field"><label for="name">First name</label><input id="name" data-field="name" value="${esc(data.name)}" autocomplete="given-name" placeholder="Your name"></div><div class="field"><label for="age">Age</label><input id="age" data-field="age" type="number" min="13" max="100" value="${esc(data.age)}" inputmode="numeric" placeholder="e.g. 30"></div><div class="field"><label for="height">Height · cm</label><input id="height" data-field="height" type="number" min="100" max="230" value="${esc(data.height)}" inputmode="decimal" placeholder="e.g. 175"></div><div class="field"><label for="weight">Weight · kg</label><input id="weight" data-field="weight" type="number" min="30" max="300" value="${esc(data.weight)}" inputmode="decimal" placeholder="e.g. 80"></div><div class="field full"><label for="sex">Sex · optional</label><select id="sex" data-field="sex"><option value="">Prefer not to say</option><option ${data.sex==='female'?'selected':''}>Female</option><option ${data.sex==='male'?'selected':''}>Male</option><option ${data.sex==='other'?'selected':''}>Other</option></select></div></div><p class="helper">Age, height and weight are optional for the first plan. We will not use them to make medical claims.</p></div>`;
if(step===3)return `<div class="step"><div class="eyebrow">03 · EXPERIENCE</div><h1>How familiar are you with training?</h1><p class="lead">This changes how we introduce movements, complexity and progression.</p>${optionList(experiences,'experience')}</div>`;
if(step===4)return `<div class="step"><div class="eyebrow">04 · REAL-LIFE SCHEDULE</div><h1>What can you actually sustain?</h1><p class="lead">Choose the schedule you can repeat, not the one you wish you had.</p><div class="fields"><div class="field"><label for="days">Training days per week</label><select id="days" data-field="days"><option value="">Choose</option>${[2,3,4,5,6,7].map(n=>`<option value="${n}" ${String(data.days)===String(n)?'selected':''}>${n} days</option>`).join('')}</select></div><div class="field"><label for="minutes">Typical session</label><select id="minutes" data-field="minutes"><option value="">Choose</option>${[20,30,45,60,75,90].map(n=>`<option value="${n}" ${String(data.minutes)===String(n)?'selected':''}>${n} minutes</option>`).join('')}</select></div></div></div>`;
if(step===5)return `<div class="step"><div class="eyebrow">05 · TRAINING ENVIRONMENT</div><h1>Where will you train?</h1><p class="lead">We use this to avoid recommending movements you cannot perform.</p>${optionList(environments,'environment')}<div style="height:18px"></div><div class="eyebrow">AVAILABLE EQUIPMENT · OPTIONAL</div><div class="choices">${equipment.map(x=>`<button class="choice ${data.equipment.includes(x)?'on':''}" data-equip="${esc(x)}"><strong>${esc(x)}</strong><span>${data.equipment.includes(x)?'Included':'Tap to include'}</span></button>`).join('')}</div></div>`;
if(step===6)return `<div class="step"><div class="eyebrow">06 · NUTRITION PREFERENCE</div><h1>How do you prefer to eat?</h1><p class="lead">We start with your preference. Detailed nutrition guidance comes later.</p><div class="choices">${diets.map(x=>`<button class="choice ${selected(data.diet,x)}" data-diet="${esc(x)}"><strong>${esc(x)}</strong><span>Used to shape practical food suggestions.</span></button>`).join('')}</div><div class="field" style="margin-top:18px"><label for="restrictions">Allergies or foods you avoid · optional</label><input id="restrictions" data-field="restrictions" value="${esc(data.restrictions)}" placeholder="e.g. peanuts, lactose"></div></div>`;
if(step===7)return review();
return finish();}
function review(){const goal=goals.find(x=>x[0]===data.goal)?.[1]||'Not selected';const exp=experiences.find(x=>x[0]===data.experience)?.[1]||'Not selected';const env=environments.find(x=>x[0]===data.environment)?.[1]||'Not selected';return `<div class="step"><div class="eyebrow">07 · REVIEW</div><h1>Your foundation is ready.</h1><p class="lead">Check the inputs before we create your starting direction. You can edit anything.</p><div class="review"><article><small>GOAL</small><strong>${esc(goal)}</strong></article><article><small>EXPERIENCE</small><strong>${esc(exp)}</strong></article><article><small>SCHEDULE</small><strong>${esc(data.days||'—')} days · ${esc(data.minutes||'—')} min</strong></article><article><small>ENVIRONMENT</small><strong>${esc(env)}</strong></article><article><small>PROFILE</small><strong>${esc(data.age||'—')} yrs · ${esc(data.height||'—')} cm · ${esc(data.weight||'—')} kg</strong></article><article><small>NUTRITION</small><strong>${esc(data.diet||'—')}</strong></article></div><p class="note">This review is the source of truth for the first plan. Nothing is silently assumed.</p></div>`}
function finish(){const goal=goals.find(x=>x[0]===data.goal);let focus=goal?.[1]||'General fitness';let structure=data.goal==='strength'?'compound strength + technique':data.goal==='muscle'?'strength + hypertrophy':data.goal==='fat'?'strength + conditioning':data.goal==='habit'?'simple full-body consistency':'balanced strength + conditioning';return `<div class="step success"><div class="mark">✓</div><div class="eyebrow">FOUNDATION COMPLETE</div><h1>Your starting direction is built.</h1><p class="lead">Fitness Guide will use this foundation to shape the next modules. Your plan starts from your reality, not a generic template.</p><div class="result"><div class="result-card"><h3>${esc(focus)}</h3><div class="planline"><span>Training structure</span><strong>${esc(structure)}</strong></div><div class="planline"><span>Frequency</span><strong>${esc(data.days)} days / week</strong></div><div class="planline"><span>Session length</span><strong>${esc(data.minutes)} minutes</strong></div><div class="planline"><span>Environment</span><strong>${esc(environments.find(x=>x[0]===data.environment)?.[1]||'Your setup')}</strong></div></div></div><p class="note">This is a starting framework, not a medical prescription. Later modules will turn it into workouts, exercise guidance, nutrition and progress tracking.</p><button class="finish" data-save="true">Save foundation & enter Fitness Guide ↗</button></div>`}
function valid(){if(step===1)return !!data.goal;if(step===2)return !data.age||(+data.age>=13&&+data.age<=100)&&(!data.height||(+data.height>=100&&+data.height<=230))&&(!data.weight||(+data.weight>=30&&+data.weight<=300));if(step===3)return !!data.experience;if(step===4)return !!data.days&&!!data.minutes;if(step===5)return !!data.environment;if(step===6)return !!data.diet;return true}
function render(){app.innerHTML=`<div class="m01"><div class="shell"><header class="top"><div class="logo"><i></i>Fitness Guide</div><div class="privacy">Local foundation · ${step<8?step===0?'Start':`${step}/7`: 'Complete'}</div></header><div class="progress"><i style="width:${pct()}%"></i></div><main class="content">${stepView()}</main>${step>0&&step<8?`<footer class="footer"><button class="back" data-back="true">← Back</button><button class="next" data-next="true" ${valid()?'':'disabled'}>${step===7?'Create my foundation':'Continue'} ↗</button></footer>`:''}</div></div>`;bind();}
function bind(){app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{data[b.dataset.choice]=b.dataset.value;render()});app.querySelectorAll('[data-diet]').forEach(b=>b.onclick=()=>{data.diet=b.dataset.diet;render()});app.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{let x=b.dataset.equip;data.equipment=data.equipment.includes(x)?data.equipment.filter(v=>v!==x):[...data.equipment,x];render()});app.querySelectorAll('[data-field]').forEach(x=>x.oninput=()=>{data[x.dataset.field]=x.value});app.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{if(!valid())return;collect();step=+b.dataset.next||step+1;render()});app.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{collect();step=Math.max(0,step-1);render()});app.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{collect();save();app.innerHTML=`<div class="m01"><div class="shell"><main class="content">${finishSaved()}</main></div></div>`;});}
function collect(){app.querySelectorAll('[data-field]').forEach(x=>data[x.dataset.field]=x.value)}
function finishSaved(){return `<div class="step success"><div class="mark">✓</div><div class="eyebrow">MODULE 01 COMPLETE</div><h1>Foundation saved.</h1><p class="lead">Your fitness profile is stored locally. The next module can now build the Today experience from this foundation.</p><div class="result-card"><div class="planline"><span>Goal</span><strong>${esc(goals.find(x=>x[0]===data.goal)?.[1])}</strong></div><div class="planline"><span>Schedule</span><strong>${esc(data.days)} days · ${esc(data.minutes)} min</strong></div><div class="planline"><span>Setup</span><strong>${esc(environments.find(x=>x[0]===data.environment)?.[1])}</strong></div></div><p class="note">Module 01 is intentionally complete before the next product module is introduced.</p></div>`}
render();
})();