(()=>{
'use strict';
const main=document.getElementById('main'),sheet=document.getElementById('sheet'),card=document.getElementById('sheet-card'),KEY='fitguide-profile';
const E=[
['march','March in place','Warm-up','2 min','Stand tall. Alternate knees and swing the opposite arm naturally. Keep a comfortable pace.','Keep your chest relaxed and breathe steadily.'],
['stepjack','Step jack','Warm-up','45 sec','Step one foot out, bring it back, then alternate sides while moving the arms comfortably.','Stay light and controlled rather than jumping.'],
['squat','Squat','Lower body','3 × 10','Stand with feet about shoulder-width apart. Sit your hips back and down, then press through the whole foot to stand.','Keep knees tracking in the same direction as your toes.'],
['box','Box squat','Lower body','3 × 10','Stand in front of a stable surface. Reach the hips back, lightly touch the surface, then stand tall.','Do not drop onto the surface or use it to bounce.'],
['lunge','Reverse lunge','Lower body','3 × 10 / side','Stand tall. Step one foot back, lower under control, then push through the front foot to return.','Use a shorter step if balance is difficult.'],
['split','Split squat','Lower body','3 × 10 / side','Take a comfortable staggered stance. Lower the back knee toward the floor, then drive through the front foot.','Keep most of your weight on the front leg.'],
['stepup','Step-up','Lower body','3 × 8 / side','Place the whole foot on a stable low step. Drive through that foot to stand, then lower slowly.','Avoid pushing hard from the trailing leg.'],
['bridge','Glute bridge','Glutes','3 × 12','Lie on your back with knees bent. Press through your feet, lift the hips, squeeze the glutes, then lower.','Finish with the hips, not by arching the lower back.'],
['singlebridge','Single-leg bridge','Glutes','3 × 10 / side','Lift one foot. Drive through the other foot to raise the hips while keeping the pelvis level.','Use a smaller range if your hips rotate.'],
['hinge','Hip hinge','Posterior chain','3 × 12','Stand tall with soft knees. Push the hips backward while keeping your spine long, then squeeze the glutes to stand.','Think hips back, not chest down.'],
['good','Good morning','Posterior chain','3 × 12','Place hands comfortably. Soften the knees, send the hips back, keep the back long, then stand.','Move slowly and stay within a comfortable range.'],
['rdl','Romanian deadlift','Posterior chain','3 × 8–10','Hold the load close. Soften the knees, push the hips back, then stand by driving the floor away.','Keep the load close to your legs throughout.'],
['goblet','Goblet squat','Lower body','3 × 8–10','Hold the weight close to your chest. Sit down between your hips, then stand through the whole foot.','Choose a load you can control for every rep.'],
['pushup','Push-up','Upper body','3 × 8–12','Set hands under or just outside the shoulders. Brace your body, lower your chest, then press the floor away.','Keep hips aligned with shoulders and heels.'],
['incline','Incline push-up','Upper body','3 × 8','Place hands on a stable elevated surface. Walk back to a straight body line, lower the chest, then press away.','Higher surface = easier. Lower surface = harder.'],
['wall','Wall push-up','Upper body','3 × 10','Face a wall with hands at chest height. Bend the elbows to bring the body toward the wall, then push away.','Keep your body straight rather than bending at the hips.'],
['row','Backpack row','Upper back','3 × 10','Hinge slightly and hold a secure backpack. Pull it toward your ribs, pause, then lower slowly.','Keep shoulders down and avoid twisting.'],
['dbrow','Dumbbell row','Upper back','3 × 10 / side','Support one hand on a stable surface. Pull the dumbbell toward the hip, then lower with control.','Keep your torso steady throughout.'],
['press','Dumbbell shoulder press','Shoulders','3 × 8–10','Start with weights near shoulder height. Press overhead smoothly, then lower under control.','Keep ribs stacked rather than leaning backward.'],
['yraise','Prone Y raise','Upper back','2 × 10','Lie face down or hinge forward. Raise straight arms into a comfortable Y, then lower slowly.','Use very light resistance or none.'],
['towel','Towel row isometric','Upper back','3 × 20 sec','Hold a towel and create steady pulling tension against your own hands. Keep the shoulders controlled.','Breathe normally and do not jerk.'],
['deadbug','Dead bug','Core','3 × 8 / side','Lie on your back with arms up and knees bent. Slowly extend the opposite arm and leg, then return.','Keep the ribs down and lower back gently supported.'],
['bird','Bird dog','Core','3 × 8 / side','From hands and knees, reach one arm and the opposite leg long. Return and switch sides.','Keep the hips square to the floor.'],
['plank','Plank','Core','3 × 20–40 sec','Set elbows or hands under the shoulders. Brace gently, squeeze the glutes and hold a straight line.','Stop before your lower back starts to sag.'],
['side','Side plank','Core','3 × 20–30 sec / side','Support yourself on the forearm or hand. Lift the hips and keep the shoulders, hips and feet stacked.','Use bent knees for an easier version.'],
['deadreach','Dead bug with reach','Core','3 × 10 / side','From the dead bug position, reach farther only while the trunk stays stable. Return and switch.','Range comes second to control.'],
['climber','Mountain climber','Conditioning','3 × 30 sec','Start in a strong high-plank position. Bring one knee toward the chest, return it, then alternate.','Keep the shoulders stable and choose a sustainable pace.'],
['fast','Fast march','Conditioning','3 × 45 sec','March briskly while driving the arms naturally. Build speed gradually.','You should still be able to control your breathing.'],
['shadow','Shadow boxing','Conditioning','3 × 45 sec','Use a comfortable stance and make light punches into the air. Move smoothly and stay relaxed.','Do not lock out the elbows aggressively.'],
['wallsit','Wall sit','Lower body','3 × 20–40 sec','Place your back against a wall and slide down to a comfortable position. Hold while breathing steadily.','Choose a knee angle you can maintain with control.'],
['calf','Calf raise','Lower legs','3 × 15','Stand tall and rise onto the balls of your feet. Pause briefly, then lower slowly.','Use a wall for balance if needed.'],
['walk','Easy walk','Recovery','5–10 min','Walk at an easy conversational pace. Let your breathing and heart rate settle gradually.','Use this as a cooldown, not a race.']
];
const by=Object.fromEntries(E.map(x=>[x[0],{id:x[0],name:x[1],area:x[2],target:x[3],how:x[4],cue:x[5]}]));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const profile=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
function stage(p){const n=+(p.completed||0);return n<8?['01','Foundation','Master movement patterns and build consistency.']:n<24?['02','Build','Add volume while keeping quality high.']:n<48?['03','Strength','Progress resistance and more challenging variations.']:['04','Performance','Progress deliberately while managing recovery.']}
function session(p){const gym=p.environment==='gym'||p.equipment==='full',adv=['intermediate','advanced'].includes(p.experience),mins=Math.max(20,+p.minutes||30);let ids=gym&&adv?['march','goblet','rdl','dbrow','press','lunge','bridge','deadbug','calf','walk']:adv?['march','squat','lunge','hinge','pushup','row','bridge','deadbug','side','fast','walk']:['march','box','bridge','incline','hinge','bird','calf','wall','fast','walk'];if(mins<=30)ids=ids.slice(0,7);else if(mins<=45)ids=ids.slice(0,9);return{mins,ids:ids.map(id=>by[id]).filter(Boolean)}}
function open(html){card.innerHTML=html;sheet.classList.add('open');sheet.setAttribute('aria-hidden','false')}
function close(){sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true')}
function train(){const p=profile(),s=stage(p),q=session(p);return `<section class="train-v6"><div class="v6-path"><span>STAGE ${s[0]}</span><strong>${s[1]}</strong><em>${+(p.completed||0)} sessions</em></div><header class="v6-head"><small>TODAY'S TRAINING</small><h1>Move well.<br>Get stronger.</h1><p>${q.mins} min · ${esc(p.environment||'home')} · ${esc(p.experience||'beginner')}</p></header><button class="v6-session" data-v6="start"><div class="v6-visual"><span>TRAIN</span><b>${q.ids.length} MOVES</b></div><div class="v6-session-copy"><small>${s[1].toUpperCase()} · TODAY</small><strong>Full body progression</strong><p>Follow each movement at your pace.</p><i>↗</i></div></button><div class="v6-heading"><div><small>YOUR SESSION</small><h2>Today's movements</h2></div><span>${q.ids.length}</span></div><div class="v6-list">${q.ids.map((x,i)=>`<button data-v6="detail" data-id="${x.id}"><i>${String(i+1).padStart(2,'0')}</i><span><strong>${esc(x.name)}</strong><small>${esc(x.target)} · ${esc(x.area)}</small></span><b>›</b></button>`).join('')}</div><div class="v6-next"><small>NEXT IN YOUR PROGRESSION</small><strong>${s[2]}</strong></div><div class="v6-heading"><div><small>EXERCISE LIBRARY</small><h2>Explore movements</h2></div><span>${E.length}</span></div><button class="v6-library" data-v6="library"><span><strong>Full exercise library</strong><small>How to perform · coaching · targets</small></span><b>↗</b></button></section>}
function detail(id){const x=by[id];if(!x)return;open(`<div class="v6-sheet"><div class="sheet-handle"></div><div class="v6-movement"><span>${esc(x.area)}</span><strong>${esc(x.name)}</strong><small>${esc(x.target)}</small></div><div class="v6-how"><small>HOW TO DO IT</small><p>${esc(x.how)}</p></div><div class="v6-coach"><small>COACHING CUE</small><strong>${esc(x.cue)}</strong></div><button class="primary" data-v6="close">Got it <span>✓</span></button></div>`)}
function library(){const groups={};E.forEach(x=>(groups[x[2]]??=[]).push(x));open(`<div class="v6-sheet library"><div class="sheet-handle"></div><small>EXERCISE LIBRARY</small><h2>Every movement.</h2><p>Open any exercise for clear instructions, target and coaching.</p>${Object.entries(groups).map(([g,list])=>`<section><small>${esc(g)}</small>${list.map(x=>`<button data-v6="detail" data-id="${x[0]}"><span><strong>${esc(x[1])}</strong><em>${esc(x[3])}</em></span><b>›</b></button>`).join('')}</section>`).join('')}</div>`)}
let items=[],wi=0;
function start(){items=session(profile()).ids;wi=0;step()}
function step(){const x=items[wi];if(!x)return finish();open(`<div class="v6-sheet workout"><div class="sheet-handle"></div><div class="v6-worktop"><small>MOVE ${wi+1} OF ${items.length}</small><b>${Math.round((wi)/items.length*100)}%</b></div><div class="v6-progress"><i style="width:${(wi+1)/items.length*100}%"></i></div><div class="v6-movement workout-art"><span>${String(wi+1).padStart(2,'0')}</span><strong>${esc(x.name)}</strong><small>${esc(x.area)} · ${esc(x.target)}</small></div><div class="v6-how"><small>DO THIS</small><p>${esc(x.how)}</p></div><div class="v6-coach"><small>KEEP IN MIND</small><strong>${esc(x.cue)}</strong></div><div class="v6-actions"><button data-v6="skip">Skip</button><button class="primary" data-v6="done">Complete <span>✓</span></button></div></div>')}
function finish(){const p=profile();p.completed=(p.completed||0)+1;localStorage.setItem(KEY,JSON.stringify(p));open(`<div class="v6-sheet complete"><div class="sheet-handle"></div><div class="v6-check">✓</div><small>SESSION COMPLETE</small><h2>Session complete.</h2><p>You finished today's planned movements. Your next session can build from this one.</p><button class="primary" data-v6="close">Back to Train <span>↗</span></button></div>`)}
window.train=train;window.FitGuideTrain={exercises:E,session,stage};
document.addEventListener('click',e=>{const t=e.target.closest('[data-v6]');if(!t)return;const a=t.dataset.v6;if(a==='start')start();else if(a==='detail')detail(t.dataset.id);else if(a==='library')library();else if(a==='done'||a==='skip'){if(wi>=items.length-1)finish();else{wi++;step()}}else if(a==='close')close()});
document.addEventListener('click',e=>{if(!e.target.closest('[data-tab="train"]'))return;requestAnimationFrame(()=>{main.innerHTML=train();main.classList.add('page-in');scrollTo(0,0)})},true);
})();